### ISSUE TITLE
[Web - React] Improve UI of Greeting website

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#11]
**Title**
Improve UI of Greeting website

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/React/Greeting-website)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [ ] Web with Html,css javascript
- [x] Web with React

**Describe the Issue**
The current UI is really bad and not user friendly , no one would visit the website second time. 

**Expected**
Improve the UI like change background color, add images/gifs/videos according to time of the day or add some small messages or quotes etc.

**Screenshots**
NA

**Additional context**
NA

**Comment by dhruv18ranjan** [comment]
Assign me this issue
