### ISSUE TITLE
[Android App- Java] Covid_19_vaccine_slot_find App - Make Sure Users only can Enter Future date or today day

### ISSUE THREAD

**Issue by maityamit** [DevilsAutumn/Hacktoberfest22#12]
**Title**
Make Sure Users only can Enter Future dates or today's day not any past dates

**Project link**
[Covid 19 App](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/App/Java/covid_19_vaccine_slot_find-master)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [x] App with Java
- [ ] App with Kotlin
- [ ] Web with Html,css javascript
- [ ] Web with React

**Describe the bug**
Make Sure Users only can Enter Future dates or today's day not any past dates

**Expected behavior**
If users enter any past date make sure there show an error.

**Comment by abhayst007** [comment]
I resolved the bug in new pull request
