### ISSUE TITLE
[Web- html,css,javascript] Allow only numbers in input field

### ISSUE THREAD

**Issue by kunal00000** [DevilsAutumn/Hacktoberfest22#18]
**Title**
Allow only number keys in code input

**Project link**
https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/verify-account-ui

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
Code verification input boxes are allowing keys other than number also. It should not take input other than number key.

**Describe the solution you'd like**
NA

**Additional context**
May I solve this issue.

**Comment by kunal00000** [comment]
please assign me this issue.

**Comment by DevilsAutumn** [comment]
What keys is it allowing except numbers?

**Comment by kunal00000** [comment]
its allowing all keyboard keys moreover focus is moving forward only on number keys but it doesn't looks nice if any other key shows up inside code verification.

**Comment by kunal00000** [comment]
<img width="778" alt="Screenshot 2022-10-04 at 3 39 17 PM" src="https://user-images.githubusercontent.com/92316166/193793551-94cbbe99-ba13-4456-99e8-550f21e366ed.png">

**Comment by DevilsAutumn** [comment]
okay go ahead.

**Comment by nikita812** [comment]
hello, I have solved this using js. Please align me with this

**Comment by DevilsAutumn** [comment]
@nikita812 hey, please don't work on the issues which are already assigned to someone. Assignment is made to prevent multiple people working on the same issue.  If someone who is already working on a issue failed to do so or doesn't response for a while then it is assigned to someone else.
