### ISSUE TITLE
To add a feature in drawing app

### ISSUE THREAD

**Issue by nikhil730** [DevilsAutumn/Hacktoberfest22#46]
**Title**
Adding a feature in drawing app so the user can take a ss of his drawing.

**Project link**
[Click here](Paste link of project here)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
In the click feature the user can draw and to keep it with him he can take a ss which will be downloaded in his pc.

**Describe the solution you'd like**
Just adding a input button to click the ss.

**Additional context**
![Screenshot (6)](https://user-images.githubusercontent.com/79016958/194399244-b254fde3-32c1-40f1-a2ef-2f22ab67dbdf.png)
![ss (4)](https://user-images.githubusercontent.com/79016958/194399287-8d5e49bf-5932-4ba5-86b4-db8b8e1bb323.png)

**Comment by DevilsAutumn** [comment]
Good going!

**Comment by nikhil730** [comment]
thankss.

**Comment by DevilsAutumn** [comment]
Pull the changes to your local repo first to avoid merge conflict.

**Comment by nikhil730** [comment]
okayy

**Comment by nikhil730** [comment]
i don't know what is wrong in this one
showing conflicting pr

**Comment by DevilsAutumn** [comment]
See i told you to Fetch the remote repo first, Now you have to do a little extra work.
1. Run ```git fetch https://github.com/DevilsAutumn/Hacktoberfest22 main```
2. Then you will see same conflicts in your local machine.
3. Accept the incoming changes and then do your changes again.
4. Then again add,commit and run ```git push -f```.

If you get stuck somewhere ask here itself .
