### ISSUE TITLE
Refs #46 - Removing firewall restrictions

### ISSUE THREAD

**Issue by saikatdgp2001** [DevilsAutumn/Hacktoberfest22#49]
**Title**
Add save button to the drawing app

**Project link**
https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/drawing-app

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
Adding the feature of save button in the drawing app will help the users to save their work .

**Describe the solution you'd like**
NA

**Additional context**
NA

**Comment by yogitha02** [comment]
@saikatdgp2001  Please do assign me i will be doing this

**Comment by Harikrishna3** [comment]
I'd like to work on this; in fact, I've already finished it. Would you kindly assign it to me?

**Comment by DevilsAutumn** [comment]
@yogitha02 @Harikrishna3 Guys the person who has opened this issue has already opened a PR . Don't worry i'll open new issues today for you .

**Comment by DevilsAutumn** [comment]
copy of #46
