### ISSUE TITLE
[Web- html,css,javascript] Add eraser to drawing app

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#5]
**Title**
Add eraser to drawing app.

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/drawing-app)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
In Drawing app currently anything that is drawn is erased all at once. Add a eraser so that user can eraser event a part of the drawing instead of whole drawing. 

**Describe the solution you'd like**
NA

**Additional context**
NA

**Comment by dhruv18ranjan** [comment]
please assign me this issue
