### ISSUE TITLE
improved the border of various reactions in feedback-ui-design

### ISSUE THREAD

**Issue by arshlakhina** [DevilsAutumn/Hacktoberfest22#52]
**Title**
Title of the Issue

**Project link**
[Click here](Paste link of project here)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [ ] Web with Html,css javascript
- [ ] Web with React

**Describe the Issue**
A clear and concise description of how the current UI is bad.

**Expected**
A clear and concise description of how you expect to improve the UI.

**Screenshots**

**Additional context**
Add any other context about the problem here else write NA.

**Comment by DevilsAutumn** [comment]
@arshlakhina hey please fill all the details in the above comment regarding the issue

**Comment by saikatdgp2001** [comment]
Sorry to say , please don't contribute as it is excluded from Hacktoberfest 2022.

**Comment by arshlakhina** [comment]
Hey
Your repo was so good, you know any reason why is it being excluded?
Still lots of useful projects in yours repo, will try to learn from them
Thanks

**Comment by DevilsAutumn** [comment]
@arshlakhina hey , thanks for the appreciation but whenever someone tries to help other there are people who do everything they can to bring them down, and here it was @saikatdgp2001 , he opened invalid pull request ([see here](https://github.com/DevilsAutumn/Hacktoberfest22/pulls?q=is%3Apr+author%3Asaikatdgp2001)) and when i closed them he blackmailed me and reported my repo. Now I just feel that i'm wasting time helping people to get started with opensource.

Anyways i have mailed to the officials regarding this , lets see what they say. Till then its upto you if you want you can keep contributing to this repo ,they might not be counted for hacktoberfest but you will definitely learn something as a beginner.

Thanks
