### ISSUE TITLE
improved the border of various reactions in feedback-ui-design   

### ISSUE THREAD

**Issue by arshlakhina** [DevilsAutumn/Hacktoberfest22#53]
**Title**
Title of the Issue

**Project link**
[Click here](Paste link of project here)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [ ] Web with Html,css javascript
- [ ] Web with React

**Describe the Issue**
A clear and concise description of how the current UI is bad.

**Expected**
A clear and concise description of how you expect to improve the UI.

**Screenshots**

**Additional context**
Add any other context about the problem here else write NA.

**Comment by DevilsAutumn** [comment]
copy of #52
