### ISSUE TITLE
[Web -html,css,javascript] - Improve UI of movies app

### ISSUE THREAD

**Issue by nikhil730** [DevilsAutumn/Hacktoberfest22#56]
**Title**
Improving the movies app ui

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/movie-app)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Describe the Issue**
Current ui is simpler with a while bg on hover for overview.

**Expected**
Changes will make the hover overview little stylish with a contrast background color and opaqe bg. 

**Screenshots**
![image](https://user-images.githubusercontent.com/79016958/194552275-2449a90e-9f71-49bd-b1b5-39ac604e7507.png)

**Additional context**
Add any other context about the problem here else write NA.

**Comment by DevilsAutumn** [comment]
Cool 👍
