### ISSUE TITLE
[Web- html,css,javascript] Add timestamp whenever user drink water.

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#6]
**Title**
Add timestamp whenever user drink water.

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/drink-water)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
Whenever user select the glass of water add a time to the right when it was selected , it will help them track the time when they drink water.

**Describe the solution you'd like**
NA

**Additional context**
NA

**Comment by shyamaljoshi1** [comment]
I added timestamp at the end of the glass , confirm me should I create a pull request or not

![image](https://user-images.githubusercontent.com/78912014/193978851-73be083b-59e4-4e18-817b-35a66cdabfbe.png)
