### ISSUE TITLE
[Web- html,css,javascript] Link Username to github profile

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#7]
**Title**
Link Username to github profile

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/github-profiles)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Please describe your feature.**
After searching for profile ,clicking on the username, users should be redirected to the profile on github.

**Describe the solution you'd like**
NA

**Additional context**
NA

**Comment by kunal00000** [comment]
Please assign this issue to me.
Happy to solve it.
