### ISSUE TITLE
[Web- html,css,javascript] Add github logo

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#8]
**Title**
Add github logo to github profiles website.

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/github-profiles)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Describe the Issue**
In github profles website there is no logo of github present.

**Expected**
Add a github logo just above search bar.

**Screenshots**
NA

**Additional context**
NA

**Comment by Pritam0077** [comment]
assign me

**Comment by DevilsAutumn** [comment]
@Pritam0077 you can also open new issues and work on it.

**Comment by Pritam0077** [comment]
I am getting access denied when trying to push my changes
<img width="440" alt="image" src="https://user-images.githubusercontent.com/89348093/193462114-4af6ba24-45b3-48ad-9982-34610955f0e4.png">

**Comment by DevilsAutumn** [comment]
You cannot push changes directly to this repo. First push changes to the forked repo then open pull request from forked repo to this repo. For more details read [contributing guide.](https://github.com/DevilsAutumn/Hacktoberfest22/blob/main/CONTRIBUTIING.md)

**Comment by Pritam0077** [comment]
done
