### ISSUE TITLE
[Web- html,css,javascript] Fix margin of list from top

### ISSUE THREAD

**Issue by DevilsAutumn** [DevilsAutumn/Hacktoberfest22#9]
**Title**
Fix margin of list from top

**Project link**
[Click here](https://github.com/DevilsAutumn/Hacktoberfest22/tree/main/Web/Html%2CCSS%2CJavascript/todo-list)

**Domain**
Add 'x' inside [ ] to cross check box.

- [ ] App with Flutter
- [ ] App with Java
- [ ] App with Kotlin
- [x] Web with Html,css javascript
- [ ] Web with React

**Describe the bug**
When new items are added in the todo list it the input box moves upwards and become invisible after certain number of items in the list.

**Expected behavior**
Expected behaviour is that list should expand to the bottom only and input box should remain fixed.

**Screenshots**
NA

**Additional context**
NA

**Comment by kunal00000** [comment]
May I solve this issue. Any more suggestion or feature you would like me to work upon in todo-app,
Please assign me this issue.
Would love to make my first pr of open source journey.

**Comment by DevilsAutumn** [comment]
Go Ahead!
